checks:
    php: true
tools:
    external_code_coverage: true
    php_analyzer: true
    php_mess_detector: true
    php_pdepend: true
    php_cpd: true
    php_hhvm: true
    php_cs_fixer:
        config: { level: psr2 }
    sensiolabs_security_checker: true
