language: php

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - MONGO_EXTENSION=mongo
    - php: 5.6
      env:
        - MONGODB_EXTENSION=mongodb
    - php: 5.6
      env:
        - MONGO_EXTENSION=mongo
        - MONGODB_EXTENSION=mongodb
        - SEND_TO_OCULAR=yes
    - php: 7.0
      env:
        - MONGODB_EXTENSION=mongodb
    - php: 7.1
      env:
        - MONGODB_EXTENSION=mongodb
    - php: nightly
      env:
        - MONGODB_EXTENSION=mongodb
    - php: hhvm

before_install:
  - bash -c 'mkdir bin'
  - travis_retry bash -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=bin'
  - bash -c 'chmod +x bin/composer.phar'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi;'

install:
  - travis_retry bash -c 'if [ "$MONGO_EXTENSION" == "mongo" ]; then yes "" | pecl -q install -f mongo-stable; fi;'
  - travis_retry bash -c 'if [ "$MONGODB_EXTENSION" == "mongodb" ]; then yes "" | pecl -q install -f mongodb-stable; fi;'
  - travis_retry ./bin/composer.phar install --ignore-platform-reqs --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - travis_retry bash -c 'if [ "$SEND_TO_OCULAR" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - travis_retry bash -c 'if [ "$SEND_TO_OCULAR" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
