language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - bash -c 'mkdir bin'
  - travis_retry bash -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=bin'
  - bash -c 'chmod +x bin/composer.phar'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi;'

install:
  - travis_retry ./bin/composer.phar install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
